services:

 
  auth-service:
    build: ./backend_java/auth-service
    ports:
      - "8090:8090"
    networks:
      - urbanops_net


  alert-service:
    build: ./backend_java/alert-service
    ports:
      - "8091:8091"
    networks:
      - urbanops_net

  trafficservice:
    build: ./backend_java/trafficservice
    ports:
      - "8092:8092"
    networks:
      - urbanops_net

 
  power-service:
    build: ./backend_java/power-service
    ports:
      - "8093:8093"
    networks:
      - urbanops_net


  cctv-service:
    build: ./backend_java/cctv-service
    ports:
      - "8094:8094"
    networks:
      - urbanops_net

  gateway-service:
    build: ./backend_java/gateway-service
    ports:
      - "8081:8081"
    depends_on:
      - auth-service
      - alert-service
      - trafficservice
      - power-service
      - cctv-service
    networks:
      - urbanops_net


  python_service:
    build: ./python/urban-operations-python
    ports:
      - "9000:9000"
    networks:
      - urbanops_net

  frontend_reactjs:
    build:
      context: ./frontend_reactjs
      dockerfile: Dockerfile
    expose:
      - "80"
    networks:
      - urbanops_net

 
  nginx_reverse_proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend_reactjs
      - gateway-service
      - python_service
    networks:
      - urbanops_net


networks:
  urbanops_net:
    driver: bridge
